name: Check out
on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: list files before
              run: ls -la
            - uses: actions/checkout@v4
            - name: list files after
              run: ls -la
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: list files before
              run: ls -la
            - name: checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: list files after
              run: ls -la